# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "custom_download_strategy"
class JangoFett < Formula
  desc ""
  homepage "https://github.com/bukukasio/homebrew-tools"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bukukasio/jango-fett/releases/download/v0.0.3/jango-fett_0.0.3_Darwin_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "be95753df92f3026f392127bbcacf920bcd54cd63c1f5a4be79c3fe12663eaf8"

      def install
        bin.install "jango-fett"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bukukasio/jango-fett/releases/download/v0.0.3/jango-fett_0.0.3_Darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "67ca93cb3efd960814ff5f89373ad5952666bde6351ce9c2196b9aa7e2aa8f24"

      def install
        bin.install "jango-fett"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bukukasio/jango-fett/releases/download/v0.0.3/jango-fett_0.0.3_Linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "6deafd0609db3a73c0ce64adb7ac57e424244f325e68200273e3ff1d25d44581"

      def install
        bin.install "jango-fett"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bukukasio/jango-fett/releases/download/v0.0.3/jango-fett_0.0.3_Linux_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "d32bf1c7aef65d5eea6b11f11e8a365c28cff6d4ad72932f47d377ecd9d7c693"

      def install
        bin.install "jango-fett"
      end
    end
  end
end
