# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "custom_download_strategy"
class Jf < Formula
  desc ""
  homepage "https://github.com/bukukasio/homebrew-tools"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bukukasio/jf/releases/download/v0.0.1/jf_0.0.1_Darwin_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "e5038a8eecfa449a1ea9fa84f26b44de510ad29b02ee53a72fe1b96f7ca7fd24"

      def install
        bin.install "jf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bukukasio/jf/releases/download/v0.0.1/jf_0.0.1_Darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "da1360ab61836debefd84205615c27c97e535e98308875eb0a954b1e7fca1af7"

      def install
        bin.install "jf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bukukasio/jf/releases/download/v0.0.1/jf_0.0.1_Linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "f451ce8089a14ce329b37a507040fdcb5be2e50c6e599973fb16f0affade30b5"

      def install
        bin.install "jf"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bukukasio/jf/releases/download/v0.0.1/jf_0.0.1_Linux_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "6ca118210c717e6c5d4e7e8f41e7797cf0170a475908fc66a1ed1fc21a2f7060"

      def install
        bin.install "jf"
      end
    end
  end
end
