# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
require_relative "custom_download_strategy"
class Jf < Formula
  desc ""
  homepage "https://github.com/bukukasio/homebrew-tools"
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bukukasio/jf/releases/download/v0.0.3/jf_0.0.3_Darwin_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "d23dd5c0aa915185f56b3b421d0fb79f2eb5db0ec7b8bd4410968828e770d43e"

      def install
        bin.install "jf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bukukasio/jf/releases/download/v0.0.3/jf_0.0.3_Darwin_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "4105a28b7635a563ed44a386a4b69de987dc478c877cb28d799ed960639e7084"

      def install
        bin.install "jf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bukukasio/jf/releases/download/v0.0.3/jf_0.0.3_Linux_arm64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "67b833b058a9ea9a4d5f029cd1a2d09b3d08e5ce1d2c9fd130c77df6ded76d89"

      def install
        bin.install "jf"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bukukasio/jf/releases/download/v0.0.3/jf_0.0.3_Linux_x86_64.tar.gz", using: GitHubPrivateRepositoryReleaseDownloadStrategy
      sha256 "8d4a7b43e366cad475f03e83fc66ac3254b5aa30ca0c9e8432c2d3f1405ad9a7"

      def install
        bin.install "jf"
      end
    end
  end
end
