# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LummoSqlproxy < Formula
  desc ""
  homepage "https://github.com/bukukasio/homebrew-tools"
  version "1.0.17"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bukukasio/lummo-sqlproxy/releases/download/v1.0.17/lummo-sqlproxy_1.0.17_Darwin_x86_64.tar.gz"
      sha256 "c7fd30b1825f16bfd9212ac27387354b3d1bf86e23e2d286861a32b87e1977f0"

      def install
        bin.install "lummo-sqlproxy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bukukasio/lummo-sqlproxy/releases/download/v1.0.17/lummo-sqlproxy_1.0.17_Darwin_arm64.tar.gz"
      sha256 "ea4ef8ee6b698c8d2857feb84a1564fd014f49ce0200cd5e8426e5c2bbe18159"

      def install
        bin.install "lummo-sqlproxy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bukukasio/lummo-sqlproxy/releases/download/v1.0.17/lummo-sqlproxy_1.0.17_Linux_arm64.tar.gz"
      sha256 "1196c829d70bec1caac9b8d968d1552742c41ea582e8f0b34395dee0220d2324"

      def install
        bin.install "lummo-sqlproxy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bukukasio/lummo-sqlproxy/releases/download/v1.0.17/lummo-sqlproxy_1.0.17_Linux_x86_64.tar.gz"
      sha256 "7bfdc92cb47c7372b1d4875939f0a4deca2b5707e8415de20ee8e1e10867418e"

      def install
        bin.install "lummo-sqlproxy"
      end
    end
  end
end
