# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LummoSqlproxy < Formula
  desc ""
  homepage "https://github.com/bukukasio/homebrew-tools"
  version "1.0.14"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bukukasio/lummo-sqlproxy/releases/download/v1.0.14/lummo-sqlproxy_1.0.14_Darwin_x86_64.tar.gz"
      sha256 "ef74a1b95178d9bb5fe5f5227491ea82cb3f71aec3b0c3e54b6178e776d9d77f"

      def install
        bin.install "lummo-sqlproxy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bukukasio/lummo-sqlproxy/releases/download/v1.0.14/lummo-sqlproxy_1.0.14_Darwin_arm64.tar.gz"
      sha256 "b5258d9e6f2c8ba0c6ed02b9fa5a070c8257165367ae234ea180f386eca5ec8a"

      def install
        bin.install "lummo-sqlproxy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bukukasio/lummo-sqlproxy/releases/download/v1.0.14/lummo-sqlproxy_1.0.14_Linux_arm64.tar.gz"
      sha256 "4aa58b0c27af963c0bd9b256b18f0448782cc5f99e13d5517d83dfbe6fd92451"

      def install
        bin.install "lummo-sqlproxy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bukukasio/lummo-sqlproxy/releases/download/v1.0.14/lummo-sqlproxy_1.0.14_Linux_x86_64.tar.gz"
      sha256 "32d44b93e35f968054e140d97b1873c9cf74759bdfe62e9c7b86b05b751203a4"

      def install
        bin.install "lummo-sqlproxy"
      end
    end
  end
end
